server:
  port: 8280

spring:
  application:
    name: java-cloud-zuul-proxy

eureka:
  client:
    service-url:  
      defaultZone: http://genvict:gv123456@localhost:8761/eureka,http://genvict:gv123456@localhost:8762/eureka
      
zuul:
  routes:
    api-a:
      path: /ws/platform/**
      serviceId: java-wbe-cloud-platform
    #java-wbe-cloud-platform: /ws/cuigl/**
  #ignored-services:     #忽略指定微服务,多个微服务之间使用逗号分隔
  retryable: true
  
ribbon:
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 0 
    