spring:
  application:
    name: java-wbe-cloud-platform
    
server:
  port: 18003
  
eureka:
  client:
    service-url:
      defaultZone: http://genvict:gv123456@localhost:8761/eureka,http://genvict:gv123456@localhost:8762/eureka   
    
    
    
    
    
    
    
    
    